spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true

  rabbitmq:
    addresses: ${RABBITMQ_URL}
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000
          multiplier: 2.0
          max-interval: 10000
        default-requeue-rejected: false

  data:
    redis:
      url: ${REDIS_URL}

  flyway:
    enabled: false

springdoc:
  api-docs:
    enabled: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: 900000
  refresh-token-expiration-ms: 2592000000